//P77
SQUAREMATRIXMULTIPLYRECURSIVE(A,B)
n=A.rows
let C be a new n*n matrix
if n==1
	c[1][1]=a[1][1]*b[1][1]
else //partition A, B, and C as in equations(4.9)
	C[1][1]=SQUAREMATRIXMULTIPLYRECURSIVE(A[1][1], B[1][1])
		    +SQUAREMATRIXMULTIPLYRECURSIVE(A[1][2], B[2][1])
	C[1][2]=SQUAREMATRIXMULTIPLYRECURSIVE(A[1][1], B[1][2])
		   +SQUAREMATRIXMULTIPLYRECURSIVE(A[1][2], B[2][2])
    C[2][1]=SQUAREMATRIXMULTIPLYRECURSIVE(A[2][1], B[1][1])
		   +SQUAREMATRIXMULTIPLYRECURSIVE(A[2][2], B[2][1])
	C[2][2]=SQUAREMATRIXMULTIPLYRECURSIVE(A[2][1], B[1][2])
		   +SQUAREMATRIXMULTIPLYRECURSIVE(A[2][2], B[2][2])
return C